include "prod.conf"

app {
  environment = "test"
  isProduction = false
}

database {
  url = ${?DATABASE_URL}
}

jwt {
  secret = "test-secret"
  expiresIn = "1d"
  secret = ${?JWT_SECRET}
  expiresIn = ${?JWT_EXPIRES_IN}
}

storage {
  region = "us-east-1"
  accessKeyId = "test"
  secretAccessKey = "test"
  endpoint = "http://localhost:4567"
  privateBucket = "ticketshub-private-dev"
  publicBucket = "ticketshub-public-dev"
}
