services:
  postgres:
    image: postgres:16-alpine
    container_name: ticketshub-db
    environment:
      POSTGRES_USER: ticketshub
      POSTGRES_PASSWORD: ticketshub
      POSTGRES_DB: ticketshub
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketshub"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: ticketshub-localstack
    ports:
      - "4567:4566"
    environment:
      SERVICES: s3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
